server:
  port: 8899

logging:
  path: logs
  file: mylog.log

spring:
  application:
    name: report
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/course
    username: root
    password: admin

mybatis:
    type-aliases-package: com.sxt.pojo
    mapper-locations:
       - mapper/*


